# Generated by Django 4.1.1 on 2022-09-11 12:19

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutTeaContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_tea', ckeditor.fields.RichTextField(default='', max_length=500000, null=True)),
                ('about_tea_en', ckeditor.fields.RichTextField(default='', max_length=500000, null=True)),
                ('about_tea_ru', ckeditor.fields.RichTextField(default='', max_length=500000, null=True)),
                ('camelia', ckeditor.fields.RichTextField(default='', max_length=500000, null=True)),
                ('camelia_en', ckeditor.fields.RichTextField(default='', max_length=500000, null=True)),
                ('camelia_ru', ckeditor.fields.RichTextField(default='', max_length=500000, null=True)),
                ('names_of_tea', ckeditor.fields.RichTextField(default='', max_length=500000, null=True)),
                ('names_of_tea_en', ckeditor.fields.RichTextField(default='', max_length=500000, null=True)),
                ('names_of_tea_ru', ckeditor.fields.RichTextField(default='', max_length=500000, null=True)),
                ('black_tea', ckeditor.fields.RichTextField(default='', max_length=500000, null=True)),
                ('black_tea_en', ckeditor.fields.RichTextField(default='', max_length=500000, null=True)),
                ('black_tea_ru', ckeditor.fields.RichTextField(default='', max_length=500000, null=True)),
                ('green_tea', ckeditor.fields.RichTextField(default='', max_length=500000, null=True)),
                ('green_tea_en', ckeditor.fields.RichTextField(default='', max_length=500000, null=True)),
                ('green_tea_ru', ckeditor.fields.RichTextField(default='', max_length=500000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankProps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(default='', max_length=500, null=True)),
                ('account_number', models.CharField(default='', max_length=500, null=True)),
                ('cardholder_name', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Name')),
                ('name_en', models.CharField(default='', max_length=100, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(default='', max_length=100, null=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Name')),
                ('name_en', models.CharField(default='', max_length=100, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(default='', max_length=100, null=True, verbose_name='Name')),
                ('description', models.TextField(default='', max_length=1000, verbose_name='Description')),
                ('description_en', models.TextField(default='', max_length=1000, null=True, verbose_name='Description')),
                ('description_ru', models.TextField(default='', max_length=1000, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Price')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='ShopPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_of_service', ckeditor.fields.RichTextField(default='', max_length=500000, null=True)),
                ('term_of_service_en', ckeditor.fields.RichTextField(default='', max_length=500000, null=True)),
                ('term_of_service_ru', ckeditor.fields.RichTextField(default='', max_length=500000, null=True)),
                ('shipping_policy', ckeditor.fields.RichTextField(default='', max_length=500000, null=True)),
                ('shipping_policy_en', ckeditor.fields.RichTextField(default='', max_length=500000, null=True)),
                ('shipping_policy_ru', ckeditor.fields.RichTextField(default='', max_length=500000, null=True)),
                ('return_policy', ckeditor.fields.RichTextField(default='', max_length=500000, null=True)),
                ('return_policy_en', ckeditor.fields.RichTextField(default='', max_length=500000, null=True)),
                ('return_policy_ru', ckeditor.fields.RichTextField(default='', max_length=500000, null=True)),
                ('privacy_policy', ckeditor.fields.RichTextField(default='', max_length=500000, null=True)),
                ('privacy_policy_en', ckeditor.fields.RichTextField(default='', max_length=500000, null=True)),
                ('privacy_policy_ru', ckeditor.fields.RichTextField(default='', max_length=500000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductToCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_to_cart', to='shop.cart', verbose_name='Cart Number')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_to_cart', to='shop.product', verbose_name='Product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name="Isn't finished")),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is paid')),
                ('shipping_first_name', models.CharField(default='', max_length=50, null=True, verbose_name='First name')),
                ('shipping_last_name', models.CharField(default='', max_length=50, null=True, verbose_name='Last name')),
                ('shipping_address', models.CharField(default='', max_length=50, null=True, verbose_name='Address')),
                ('shipping_city', models.CharField(default='', max_length=50, null=True, verbose_name='City')),
                ('shipping_province', models.CharField(choices=[('BANGKOK', (('Bangkok', 'Bangkok (กรุงเทพมหานคร)'), ('Nakhon Nayok', 'Nakhon Nayok (นครนายก)'), ('Nonthaburi', 'Nonthaburi (นนทบุรี)'), ('Pathum Thani', 'Pathum Thani (ปทุมธานี)'), ('Samut Prakan', 'Samut Prakan (สมุทรปราการ)'))), ('NORTH', (('Chiang Mai', 'Chiang Mai (เชียงใหม่)'), ('Chiang Rai', 'Chiang Rai (เชียงราย)'), ('Lampang', 'Lampang (ลำปาง)'), ('Lamphun', 'Lamphun (ลำพูน)'), ('Mae Hong Son', 'Mae Hong Son (แม่ฮ่องสอน)'), ('Nan', 'Nan (น่าน)'), ('Phayao', 'Phayao (พะเยา)'), ('Phrae', 'Phrae (แพร่)'), ('Uttaradit', 'Uttaradit (อุตรดิตถ์)'))), ('ISAN', (('Amnat Charoen', 'Amnat Charoen (อำนาจเจริญ)'), ('Bueng Kan', 'Bueng Kan (บึงกาฬ)'), ('Buriram', 'Buriram (บุรีรัมย์)'), ('Chaiyaphum', 'Chaiyaphum (ชัยภูมิ)'), ('Kalasin', 'Kalasin (กาฬสินธุ์)'), ('Khon Kaen', 'Khon Kaen (ขอนแก่น)'), ('Loei', 'Loei (เลย)'), ('Maha Sarakham', 'Maha Sarakham (มหาสารคาม)'), ('Mukdahan', 'Mukdahan (มุกดาหาร)'), ('Nakhon Phanom', 'Nakhon Phanom (นครพนม)'), ('Nakhon Ratchasima', 'Nakhon Ratchasima (นครราชสีมา)'), ('Nong Bua Lamphu', 'Nong Bua Lamphu (หนองบัวลำภู)'), ('Nong Khai', 'Nong Khai (หนองคาย)'), ('Roi Et', 'Roi Et (ร้อยเอ็ด)'), ('Sakon Nakhon', 'Sakon Nakhon (สกลนคร)'), ('Si Sa Ket', 'Si Sa Ket (ศรีสะเกษ)'), ('Surin', 'Surin (สุรินทร์)'), ('Ubon Ratchathani', 'Ubon Ratchathani (อุบลราชธานี)'), ('Udon Thani', 'Udon Thani (อุดรธานี)'), ('Yasothon', 'Yasothon (ยโสธร)'))), ('CENTER', (('Ang Thong', 'Ang Thong (อ่างทอง)'), ('Ayutthaya', 'Ayutthaya (พระนครศรีอยุธยา)'), ('Chai Nat', 'Chai Nat (ชัยนาท)'), ('Kamphaeng Phet', 'Kamphaeng Phet (กำแพงเพชร)'), ('Lop Buri', 'Lop Buri (ลพบุรี)'), ('Nakhon Sawan', 'Nakhon Sawan (นครสวรรค)'), ('Phetchabun', 'Phetchabun (เพชรบูรณ์)'), ('Phichit', 'Phichit (พิจิตร)'), ('Phitsanulok', 'Phitsanulok (พิษณุโลก)'), ('Saraburi', 'Saraburi (สระบุรี)'), ('Sing Buri', 'Sing Buri (สิงห์บุรี)'), ('Sukhothai', 'Sukhothai (สุโขทัย)'), ('Tak', 'Tak (ตาก)'), ('Uthai Thani', 'Uthai Thani (อุทัยธานี)'))), ('WEST', (('Kanchanaburi', 'Kanchanaburi (กาญจนบุรี)'), ('Nakhon Pathom', 'Nakhon Pathom (นครปฐม)'), ('Ratchaburi', 'Ratchaburi (ราชบุรี)'), ('Samut Sakhon', 'Samut Sakhon (สมุทรสาคร)'), ('Samut Songkhram', 'Samut Songkhram (สมุทรสงคราม)'), ('Suphan Buri', 'Suphan Buri (สุพรรณบุรี)'))), ('EAST', (('Chachoengsao', 'Chachoengsao (ฉะเชิงเทรา)'), ('Chantaburi', 'Chantaburi (จันทบุรี)'), ('Chonburi', 'Chonburi (ชลบุรี)'), ('Prachinburi', 'Prachinburi (ปราจีนบุรี)'), ('Rayong', 'Rayong (ระยอง)'), ('Sa Kaeo', 'Sa Kaeo (สระแก้ว)'), ('Trat', 'Trat (ตราด)'))), ('SOUTH', (('Chumphon', 'Chumphon (ชุมพร)'), ('Krabi', 'Krabi (กระบี่)'), ('Nakhon Si Thammarat', 'Nakhon Si Thammarat (นครศรีธรรมราช)'), ('Narathiwat', 'Narathiwat (นราธิวาส)'), ('Pattani', 'Pattani (ปัตตานี)'), ('Phang Nga', 'Phang Nga (พังงา)'), ('Phattalung', 'Phattalung (พัทลุง)'), ('Phetchaburi', 'Phetchaburi (เพชรบุรี)'), ('Phuket', 'Phuket (ภูเก็ต)'), ('Prachuap Khiri Khan', 'Prachuap Khiri Khan (ประจวบคีรีขันธ์)'), ('Ranong', 'Ranong (ระนอง)'), ('Satun', 'Satun (สตูล)'), ('Songkhla', 'Songkhla (สงขลา)'), ('Surat Thani', 'Surat Thani (สุราษฎร์ธานี)'), ('Trang', 'Trang (ตรัง)'), ('Yala', 'Yala (ยะลา)')))], max_length=50, null=True, verbose_name='Province')),
                ('shipping_postal', models.CharField(default='', max_length=50, null=True, verbose_name='Postal')),
                ('shipping_phone', models.CharField(default='', max_length=50, null=True, verbose_name='Phone')),
                ('billing_first_name', models.CharField(default='', max_length=50, null=True, verbose_name='First Name')),
                ('billing_last_name', models.CharField(default='', max_length=50, null=True, verbose_name='Last name')),
                ('billing_address', models.CharField(default='', max_length=50, null=True, verbose_name='Address')),
                ('billing_city', models.CharField(default='', max_length=50, null=True, verbose_name='City')),
                ('billing_province', models.CharField(choices=[('BANGKOK', (('Bangkok', 'Bangkok (กรุงเทพมหานคร)'), ('Nakhon Nayok', 'Nakhon Nayok (นครนายก)'), ('Nonthaburi', 'Nonthaburi (นนทบุรี)'), ('Pathum Thani', 'Pathum Thani (ปทุมธานี)'), ('Samut Prakan', 'Samut Prakan (สมุทรปราการ)'))), ('NORTH', (('Chiang Mai', 'Chiang Mai (เชียงใหม่)'), ('Chiang Rai', 'Chiang Rai (เชียงราย)'), ('Lampang', 'Lampang (ลำปาง)'), ('Lamphun', 'Lamphun (ลำพูน)'), ('Mae Hong Son', 'Mae Hong Son (แม่ฮ่องสอน)'), ('Nan', 'Nan (น่าน)'), ('Phayao', 'Phayao (พะเยา)'), ('Phrae', 'Phrae (แพร่)'), ('Uttaradit', 'Uttaradit (อุตรดิตถ์)'))), ('ISAN', (('Amnat Charoen', 'Amnat Charoen (อำนาจเจริญ)'), ('Bueng Kan', 'Bueng Kan (บึงกาฬ)'), ('Buriram', 'Buriram (บุรีรัมย์)'), ('Chaiyaphum', 'Chaiyaphum (ชัยภูมิ)'), ('Kalasin', 'Kalasin (กาฬสินธุ์)'), ('Khon Kaen', 'Khon Kaen (ขอนแก่น)'), ('Loei', 'Loei (เลย)'), ('Maha Sarakham', 'Maha Sarakham (มหาสารคาม)'), ('Mukdahan', 'Mukdahan (มุกดาหาร)'), ('Nakhon Phanom', 'Nakhon Phanom (นครพนม)'), ('Nakhon Ratchasima', 'Nakhon Ratchasima (นครราชสีมา)'), ('Nong Bua Lamphu', 'Nong Bua Lamphu (หนองบัวลำภู)'), ('Nong Khai', 'Nong Khai (หนองคาย)'), ('Roi Et', 'Roi Et (ร้อยเอ็ด)'), ('Sakon Nakhon', 'Sakon Nakhon (สกลนคร)'), ('Si Sa Ket', 'Si Sa Ket (ศรีสะเกษ)'), ('Surin', 'Surin (สุรินทร์)'), ('Ubon Ratchathani', 'Ubon Ratchathani (อุบลราชธานี)'), ('Udon Thani', 'Udon Thani (อุดรธานี)'), ('Yasothon', 'Yasothon (ยโสธร)'))), ('CENTER', (('Ang Thong', 'Ang Thong (อ่างทอง)'), ('Ayutthaya', 'Ayutthaya (พระนครศรีอยุธยา)'), ('Chai Nat', 'Chai Nat (ชัยนาท)'), ('Kamphaeng Phet', 'Kamphaeng Phet (กำแพงเพชร)'), ('Lop Buri', 'Lop Buri (ลพบุรี)'), ('Nakhon Sawan', 'Nakhon Sawan (นครสวรรค)'), ('Phetchabun', 'Phetchabun (เพชรบูรณ์)'), ('Phichit', 'Phichit (พิจิตร)'), ('Phitsanulok', 'Phitsanulok (พิษณุโลก)'), ('Saraburi', 'Saraburi (สระบุรี)'), ('Sing Buri', 'Sing Buri (สิงห์บุรี)'), ('Sukhothai', 'Sukhothai (สุโขทัย)'), ('Tak', 'Tak (ตาก)'), ('Uthai Thani', 'Uthai Thani (อุทัยธานี)'))), ('WEST', (('Kanchanaburi', 'Kanchanaburi (กาญจนบุรี)'), ('Nakhon Pathom', 'Nakhon Pathom (นครปฐม)'), ('Ratchaburi', 'Ratchaburi (ราชบุรี)'), ('Samut Sakhon', 'Samut Sakhon (สมุทรสาคร)'), ('Samut Songkhram', 'Samut Songkhram (สมุทรสงคราม)'), ('Suphan Buri', 'Suphan Buri (สุพรรณบุรี)'))), ('EAST', (('Chachoengsao', 'Chachoengsao (ฉะเชิงเทรา)'), ('Chantaburi', 'Chantaburi (จันทบุรี)'), ('Chonburi', 'Chonburi (ชลบุรี)'), ('Prachinburi', 'Prachinburi (ปราจีนบุรี)'), ('Rayong', 'Rayong (ระยอง)'), ('Sa Kaeo', 'Sa Kaeo (สระแก้ว)'), ('Trat', 'Trat (ตราด)'))), ('SOUTH', (('Chumphon', 'Chumphon (ชุมพร)'), ('Krabi', 'Krabi (กระบี่)'), ('Nakhon Si Thammarat', 'Nakhon Si Thammarat (นครศรีธรรมราช)'), ('Narathiwat', 'Narathiwat (นราธิวาส)'), ('Pattani', 'Pattani (ปัตตานี)'), ('Phang Nga', 'Phang Nga (พังงา)'), ('Phattalung', 'Phattalung (พัทลุง)'), ('Phetchaburi', 'Phetchaburi (เพชรบุรี)'), ('Phuket', 'Phuket (ภูเก็ต)'), ('Prachuap Khiri Khan', 'Prachuap Khiri Khan (ประจวบคีรีขันธ์)'), ('Ranong', 'Ranong (ระนอง)'), ('Satun', 'Satun (สตูล)'), ('Songkhla', 'Songkhla (สงขลา)'), ('Surat Thani', 'Surat Thani (สุราษฎร์ธานี)'), ('Trang', 'Trang (ตรัง)'), ('Yala', 'Yala (ยะลา)')))], default='', max_length=50, null=True, verbose_name='Province')),
                ('billing_postal', models.CharField(default='', max_length=50, null=True, verbose_name='Postal')),
                ('billing_phone', models.CharField(default='', max_length=50, null=True, verbose_name='Phone')),
                ('cart', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='shop.cart', verbose_name='Cart Number')),
            ],
        ),
    ]
